apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-pbaknxxq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-pbaknxxq:azure-162fd9fa12228f3eee0e69455532764eeda9d2f0
          name: container-image
